    - name: pass variables to config.yaml files
      template: src=userconfig.yaml dest=/var/lib/vz/snippets/userconfig.yaml
      vars:
        myciuser: "{{ hostvars['localhost']['devUser'] }}"
        mysshkeys: "{{ hostvars['localhost']['playbook_idrsa2'] }}"

    - name: pass variables to config.yaml files
      template: src=networkconfig.yaml dest=/var/lib/vz/snippets/networkconfig.yaml

    - name: Cloning virtual machine from "{{ VM_template }}" with name "{{ VM_name }}"
      proxmox_kvm:
        api_user : "{{ api_user }}"
        api_password: "{{ PV_password }}" 
        api_host : "{{ default_proxmox_node }}"
        name : "{{ VM_name }}"
        node : "{{ default_proxmox_node }}"
        clone: "{{ VM_template }}"
        newid: "{{ VM_ID }}"
        timeout: 300
      tags: provission

    - name: Set the VM cloud-config
      shell: A=$(qm list |grep "{{ VM_name }}" | awk '{print $1}'); qm set $A --cicustom "network=local:snippets/networkconfig.yaml,user=local:snippets/userconfig.yaml"

    - name: Increasing disk if it is necessary
      shell: A=$(qm list |grep "{{ VM_name }}" | awk '{print $1}'); qm resize $A {{ default_disk }} +{{ VM_INCREASE_DISK }}G
      when: '"{{ VM_INCREASE_DISK }}" != "0"'
      tags: provission

    - name: Waiting to apply cloud init changes in disk
      wait_for:
        host: "{{ VM_name }}"
        timeout: 5
      tags: provission

    - name: starting new Virtual Machine
      proxmox_kvm:
        api_user : "{{ api_user }}"
        api_password: "{{ PV_password }}" 
        api_host : "{{ default_proxmox_node }}"
        name : "{{ VM_name }}"
        node : "{{ default_proxmox_node }}"
        state : started
        timeout: 300
      when: '"{{ VM_INCREASE_DISK }}" != "0"' 
      register: wait
      tags: provission

    - name: Waiting to start virtual server machine completely
      wait_for: 
        host: "{{ VM_name }}"
        timeout: 15
      when: wait.changed == true
      tags: provission

    - name: stopping new Virtual Machine to change disk space, it is necessary
      shell: A=$(qm list |grep "{{ VM_name }}" | awk '{print $1}'); qm stop $A
      when: '"{{ VM_network }}" != "my_network" or "{{ VM_INCREASE_DISK }}" != "0"'
      tags: provission

    - name: Waiting to stop virtual server machine completely
      wait_for: 
        host: "{{ VM_name }}"
        timeout: 15
      when: wait.changed == true
      tags: provission

    - name: starting new Virtual Machine in current proxmox node
      proxmox_kvm: 
        api_user : "{{ api_user }}"
        api_password: "{{ PV_password }}"
        api_host : "{{ default_proxmox_node }}"
        name : "{{ VM_name }}"
        node : "{{ default_proxmox_node }}"
        state : started
        timeout: 300
      when: '"{{ PV_node2 }}" == "none"'
      tags: provission

    - name: starting new Virtual Machine in correct proxmox node
      proxmox_kvm:
        api_user : "{{ api_user }}"
        api_password: "{{ PV_password }}"
        api_host : "{{ default_proxmox_node }}"
        name : "{{ VM_name }}"
        node : "{{ PV_node2 }}"
        state : started
        timeout: 300
      delegate_to: "{{ PV_node2 }}"
      when: '"{{ PV_node2 }}" != "none"'
      tags: provission
      